import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar do Aplica DS docs.
 *
 * Os prefixos numéricos (01-, 02-…) nos nomes de arquivo garantem a ordem
 * correta dentro de cada seção. Os labels aqui são os nomes legíveis das seções.
 *
 * Para traduzir os labels de categoria, criar:
 *   i18n/en/docusaurus-plugin-content-docs/current.json
 */
const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'category',
      label: '00 · Visão Geral',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: '00-overview' }],
    },
    {
      type: 'category',
      label: '01 · Fundamentos de Tokens',
      items: [{ type: 'autogenerated', dirName: '01-design-tokens-fundamentals' }],
    },
    {
      type: 'category',
      label: '02 · Camadas de Tokens',
      items: [{ type: 'autogenerated', dirName: '02-token-layers' }],
    },
    {
      type: 'category',
      label: '03 · Fundações Visuais',
      items: [{ type: 'autogenerated', dirName: '03-visual-foundations' }],
    },
    {
      type: 'category',
      label: '04 · Theme Engine',
      items: [{ type: 'autogenerated', dirName: '04-theme-engine' }],
    },
    {
      type: 'category',
      label: '05 · Teoria de Componentes',
      items: [{ type: 'autogenerated', dirName: '05-components-theory' }],
    },
    {
      type: 'category',
      label: '06 · Histórico',
      items: [{ type: 'autogenerated', dirName: '06-history' }],
    },
    {
      type: 'category',
      label: '07 · Implementação',
      items: [{ type: 'autogenerated', dirName: '07-implementation' }],
    },
    {
      type: 'category',
      label: '08 · Tutoriais',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'N1 · Product Designer',
          items: [{ type: 'autogenerated', dirName: '08-tutorials/n1-product-designer' }],
        },
        {
          type: 'category',
          label: 'N2 · System Designer',
          items: [{ type: 'autogenerated', dirName: '08-tutorials/n2-system-designer' }],
        },
        {
          type: 'category',
          label: 'N3 · Design Engineer',
          items: [{ type: 'autogenerated', dirName: '08-tutorials/n3-design-engineer' }],
        },
      ],
    },
  ],
};

export default sidebars;
