import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar do Aplica DS — organizado por público-alvo.
 *
 * Duas trilhas principais:
 *   "Usar o Pacote NPM"  — instalar, configurar e consumir @aplica/aplica-theme-engine
 *   "Entender o Sistema" — modelo mental, camadas e fundações conceituais
 *
 * Labels EN em: i18n/en-US/docusaurus-plugin-content-docs/current.json
 */
const sidebars: SidebarsConfig = {
  mainSidebar: [

    // ── ENTRADA ──────────────────────────────────────────────────────
    {
      type: 'category',
      label: 'Visão Geral',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: '00-overview' }],
    },

    // ── CAMINHO: USAR O PACOTE NPM ───────────────────────────────────
    {
      type: 'category',
      label: 'Usar o Pacote NPM',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/npm',
        title: 'Usar o Pacote NPM',
        description: 'Documentação técnica para instalar, configurar e consumir o @aplica/aplica-theme-engine.',
      },
      items: [
        {
          type: 'category',
          label: 'Quick Start & Configuração',
          link: { type: 'generated-index', slug: '/npm/configuracao' },
          items: [{ type: 'autogenerated', dirName: '09-engineering' }],
        },
        {
          type: 'category',
          label: 'Consumo e Integração',
          link: { type: 'generated-index', slug: '/npm/consumo' },
          items: [{ type: 'autogenerated', dirName: '07-implementation' }],
        },
      ],
    },

    // ── CAMINHO: ENTENDER O SISTEMA ──────────────────────────────────
    {
      type: 'category',
      label: 'Entender o Sistema',
      link: {
        type: 'generated-index',
        slug: '/sistema',
        title: 'Entender o Sistema',
        description: 'Modelo mental, arquitetura de camadas e fundações conceituais do Aplica DS.',
      },
      items: [
        { type: 'autogenerated', dirName: '01-design-tokens-fundamentals' },
        {
          type: 'category',
          label: 'Camadas de Tokens',
          items: [{ type: 'autogenerated', dirName: '02-token-layers' }],
        },
        {
          type: 'category',
          label: 'Fundações Visuais',
          items: [{ type: 'autogenerated', dirName: '03-visual-foundations' }],
        },
        {
          type: 'category',
          label: 'Theme Engine',
          items: [{ type: 'autogenerated', dirName: '04-theme-engine' }],
        },
        {
          type: 'category',
          label: 'Teoria de Componentes',
          items: [{ type: 'autogenerated', dirName: '05-components-theory' }],
        },
        {
          type: 'category',
          label: 'Histórico',
          items: [{ type: 'autogenerated', dirName: '06-history' }],
        },
      ],
    },

    // ── TUTORIAIS ────────────────────────────────────────────────────
    {
      type: 'category',
      label: 'Tutoriais',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'N1 · Product Designer',
          items: [{ type: 'autogenerated', dirName: '08-tutorials/n1-product-designer' }],
        },
        {
          type: 'category',
          label: 'N2 · System Designer',
          items: [{ type: 'autogenerated', dirName: '08-tutorials/n2-system-designer' }],
        },
        {
          type: 'category',
          label: 'N3 · Design Engineer',
          items: [{ type: 'autogenerated', dirName: '08-tutorials/n3-design-engineer' }],
        },
      ],
    },

  ],
};

export default sidebars;
